import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.scss";
import Head from "next/head";
import HomeProvider from "./_provider/HomeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <link
          data-minify="1"
          rel="stylesheet"
          id="fontawesome-stars-css"
          href="https://themes-themegoods.b-cdn.net/grandtour/demo/wp-content/cache/min/1/grandtour/demo/wp-content/plugins/grandtour-custom-post/css/fontawesome-stars-o.css?ver=1661060022"
          type="text/css"
          media="all"
        />
      </Head>
      <html lang="en">
        <body className={inter.className}>
          <HomeProvider>{children}</HomeProvider>
        </body>
      </html>
    </>
  );
}
